// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCL21pmxuvWtEqdaWqF9KTLYRehU5V1tjQ',
    appId: '1:420813571442:web:c4e9899c706b8ba5a1c9eb',
    messagingSenderId: '420813571442',
    projectId: 'crud-2f74d',
    authDomain: 'crud-2f74d.firebaseapp.com',
    databaseURL: 'https://crud-2f74d-default-rtdb.firebaseio.com',
    storageBucket: 'crud-2f74d.firebasestorage.app',
    measurementId: 'G-FR6BC293L7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAm5kITIQDL3RKsDlR96VEhWG1EVm74bc',
    appId: '1:420813571442:android:30e8368f70ba43e4a1c9eb',
    messagingSenderId: '420813571442',
    projectId: 'crud-2f74d',
    databaseURL: 'https://crud-2f74d-default-rtdb.firebaseio.com',
    storageBucket: 'crud-2f74d.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDk2SCqA_aywsY0SVwmxAQYdLCyaANSlxg',
    appId: '1:420813571442:ios:1f30a02824ab9cafa1c9eb',
    messagingSenderId: '420813571442',
    projectId: 'crud-2f74d',
    databaseURL: 'https://crud-2f74d-default-rtdb.firebaseio.com',
    storageBucket: 'crud-2f74d.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDk2SCqA_aywsY0SVwmxAQYdLCyaANSlxg',
    appId: '1:420813571442:ios:1f30a02824ab9cafa1c9eb',
    messagingSenderId: '420813571442',
    projectId: 'crud-2f74d',
    databaseURL: 'https://crud-2f74d-default-rtdb.firebaseio.com',
    storageBucket: 'crud-2f74d.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );
}
